### ISSUE TITLE
Mac OS can't pip install vowpalwabbit

### ISSUE THREAD

**Issue by haobo-chen** [VowpalWabbit/vowpal_wabbit#2089]
#### Describe the bug
Got error running `pip install vowpalwabbit` in Max OS 10.14.6 with python 3.7

#### To Reproduce
```
brew install cmake
brew install boost
brew install boost-python3
pip install vowpalwabbit
```

#### Expected behavior
Install succeed

#### Observed Behavior
```
running install
running bdist_egg
running egg_info
creating python/vowpalwabbit.egg-info
writing python/vowpalwabbit.egg-info/PKG-INFO
writing dependency_links to python/vowpalwabbit.egg-info/dependency_links.txt
writing top-level names to python/vowpalwabbit.egg-info/top_level.txt
writing manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
reading manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'rapidjson'
warning: no files found matching 'python/*.dll' under directory 'python/bin'
warning: no files found matching 'python/packages.config' under directory 'python/windows*'
warning: no files found matching 'python/*.vcxproj*' under directory 'python/windows*'
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'python/vowpalwabbit.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.13-x86_64-3.7
creating build/lib.macosx-10.13-x86_64-3.7/vowpalwabbit
copying python/vowpalwabbit/pyvw.py -> build/lib.macosx-10.13-x86_64-3.7/vowpalwabbit
copying python/vowpalwabbit/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/vowpalwabbit
copying python/vowpalwabbit/sklearn_vw.py -> build/lib.macosx-10.13-x86_64-3.7/vowpalwabbit
copying python/vowpalwabbit/conda_install.sh -> build/lib.macosx-10.13-x86_64-3.7/vowpalwabbit
running build_ext
creating build/temp.macosx-10.13-x86_64-3.7
cmake -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3.7 -DBUILD_PYTHON=On -DBUILD_TESTS=Off -DWARNINGS=Off -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/appfolio/src/vowpal_wabbit/build/lib.macosx-10.13-x86_64-3.7 /Users/appfolio/src/vowpal_wabbit
CMake Warning (dev) at CMakeLists.txt:4 (set):
  implicitly converting 'TYPE' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- VowpalWabbit Version: 8.7.0
-- Found Git: /usr/local/bin/git (found version "2.10.2")
-- Git Version: 7c17556
-- Number of processors: 8
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Warning at /usr/local/lib/cmake/boost_program_options-1.71.0/libboost_program_options-variant-shared.cmake:59 (message):
  Target Boost::program_options already has an imported location
  '/usr/local/lib/libboost_program_options-mt.dylib', which will be
  overwritten with '/usr/local/lib/libboost_program_options.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_program_options-1.71.0/boost_program_options-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:155 (find_package)


CMake Warning at /usr/local/lib/cmake/boost_system-1.71.0/libboost_system-variant-shared.cmake:59 (message):
  Target Boost::system already has an imported location
  '/usr/local/lib/libboost_system-mt.dylib', which will be overwritten with
  '/usr/local/lib/libboost_system.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_system-1.71.0/boost_system-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:155 (find_package)


CMake Warning at /usr/local/lib/cmake/boost_unit_test_framework-1.71.0/libboost_unit_test_framework-variant-shared.cmake:59 (message):
  Target Boost::unit_test_framework already has an imported location
  '/usr/local/lib/libboost_unit_test_framework-mt.dylib', which will be
  overwritten with '/usr/local/lib/libboost_unit_test_framework.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_unit_test_framework-1.71.0/boost_unit_test_framework-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:155 (find_package)


-- Found Boost: /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components:  program_options system thread unit_test_framework
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11")
-- Submodule update
Submodule 'rapidjson' (https://github.com/Tencent/rapidjson.git) registered for path 'rapidjson'
Cloning into '/Users/appfolio/src/vowpal_wabbit/rapidjson'...
Submodule path 'rapidjson': checked out 'f54b0e47a08782a6131cc3d60f94d038fa6e0a51'
Submodule 'thirdparty/gtest' (https://github.com/google/googletest.git) registered for path 'rapidjson/thirdparty/gtest'
Cloning into '/Users/appfolio/src/vowpal_wabbit/rapidjson/thirdparty/gtest'...
Submodule path 'rapidjson/thirdparty/gtest': checked out '0a439623f75c029912728d80cb7f1b8b48739ca4'
-- help2man not found, please install it to generate manpages
-- Python 3.7 will be used for VowpalWabbit Python bindings
-- Found PythonInterp: /Users/appfolio/vw_env/bin/python3.7 (found suitable version "3.7.3", minimum required is "3.7")
-- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib (found suitable version "3.7.4", minimum required is "3.7")
CMake Error at /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_python"
  (requested version 1.71.0) with any of the following names:

    boost_pythonConfig.cmake
    boost_python-config.cmake

  Add the installation prefix of "boost_python" to CMAKE_PREFIX_PATH or set
  "boost_python_DIR" to a directory containing one of the above files.  If
  "boost_python" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  python/CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/appfolio/src/vowpal_wabbit/build/temp.macosx-10.13-x86_64-3.7/CMakeFiles/CMakeOutput.log".
error: command 'cmake' failed with exit status 1
```

#### Environment
Mac OS 10.14.6
python 3.7.3
cmake 3.15.3
boost 1.71.0
boost-python3

**Comment by jackgerrits** [comment]
@peterychang

**Comment by peterychang** [comment]
I'm unable to reproduce the error on my setup, but it looks like there is a problem between some versions of cmake and boost.

First, can you try updating brew and upgrading cmake, boost, and boost-python3?
If that doesn't work, try setting the following variable and building again
`export Boost_NO_BOOST_CMAKE=ON`

**Comment by haobo-chen** [comment]
@peterychang I think I'm already on the latest versions for `cmake`, `boost` and `boost-python3`. I also tried `export Boost_NO_BOOST_CMAKE=ON` but still the same error. Could you provide your versions in your environment?

**Comment by peterychang** [comment]
@haobo-chen I was using versions of those libraries that were provided by Anaconda. However, there appears to be problems with Anaconda-installed boost libraries and system-installed boost libraries, so I do not suggest using it until this problem is resolved.

I've created a PR that will fix the problem you are seeing. You can pull the branch (or wait until its merged into master) and build the library from source. Otherwise you will need to wait for the next python release

**Comment by peterychang** [comment]
The PR has been merged into master and will be available via pip on our next release. You can pick up the change now by building from source.

Marking this issue as resolved

**Comment by peterychang** [comment]
VW 8.8.0 has been released on pypi.
`pip install vowpalwabbit` should now work on OSX.
**NOTE**: Vowpalwabbit will fail to build or run on MacOS 10.14 or later due to https://github.com/VowpalWabbit/vowpal_wabbit/issues/2100

**Comment by vumaasha** [comment]
@peterychang this still not working in MacOS 10.14.6. Do you have any plans to make the installation easy for mac users?

**Comment by peterychang** [comment]
@vumaasha yes, we are actively working on a change that should make VW installation a much simpler and more streamlined operation for Linux and MacOS. Specifically we are working on removing our dependency on boost and the C++ libraries for the python bindings layer, which should alleviate any issues installing with Anaconda and should allow us a way to provide binary wheels in the future.

Please note that the only known MacOS issues occur due to binary incompatibilities between MacOS 10.14+ and Anaconda. VW should not have any issues if installed on top of a Brew environment
